# AUTOGENERATED FROM:
#     'queries/users/create_user.edgeql'
#     'queries/users/get_user_by_email.edgeql'
#     'queries/users/get_user_by_username.edgeql'
# WITH:
#     $ edgedb-py --file db.py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class GetUserByEmailResult(NoPydanticValidation):
    id: uuid.UUID
    username: str
    email: str
    first_name: str
    last_name: str
    password_hash: str
    disabled: bool


async def create_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    email: str,
    first_name: str,
    last_name: str,
    password_hash: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        INSERT User {
          username := <str>$name,
          email := <str>$email,
          first_name := <str>$first_name,
          last_name := <str>$last_name,
          password_hash := <str>$password_hash,
        };\
        """,
        name=name,
        email=email,
        first_name=first_name,
        last_name=last_name,
        password_hash=password_hash,
    )


async def get_user_by_email(
    executor: edgedb.AsyncIOExecutor,
    *,
    email: str,
) -> list[GetUserByEmailResult]:
    return await executor.query(
        """\
        SELECT User {
        	id,
        	username,
        	email,
        	first_name,
        	last_name,
        	password_hash,
        	disabled
        } FILTER .email = <str>$email;\
        """,
        email=email,
    )


async def get_user_by_username(
    executor: edgedb.AsyncIOExecutor,
    *,
    username: str,
) -> GetUserByEmailResult | None:
    return await executor.query_single(
        """\
        SELECT User {
        	id,
        	username,
        	email,
        	first_name,
        	last_name,
        	password_hash,
        	disabled
        } FILTER .username = <str>$username;\
        """,
        username=username,
    )
